### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by nisch100** [skoblov-lab/SciLK#16]
For some reason python setup.py gives me a compilation error

File "setup.py", line 19, in <module>
    packages=find_packages("./"),
  File "C:\Users\nisch100\Anaconda3\lib\site-packages\setuptools\__init__.py", line 66, in find
    convert_path(where),
  File "C:\Users\nisch100\Anaconda3\lib\distutils\util.py", line 127, in convert_path
    raise ValueError("path '%s' cannot end with '/'" % pathname)
ValueError: path './' cannot end with '/'

Am I doing something wrong?

**Comment by grayfall** [comment]
@nisch100 Thanks for reporting the issue. It seems like you are running on Windows. We've only tested the published software on Unix-like operating systems (Linux and Mac OS X) so far, and the issue you've experienced is clearly Windows-specific. I'll try to get a Windows machine to work on this. I'll contact you shortly.

**Comment by nisch100** [comment]
Hi @grayfall  I've tried using this on Linux sub-system on my PC but  it gives me a 
no setuptools module error.

pip install doesn't work so I'm not sure what's wrong.

**Comment by grayfall** [comment]
@nisch100 I've experienced no problems running SciLK via WSL. This is a detailed overview of all the things I've done. Let me know, if something is not clear enough.

1. I configured a VMware Fusion virtual machine running the latest version of Windows (as of this day). [This step is not relevant in your case, because you are running Windows natively].
2. I installed the WSL Ubuntu distribution via Microsoft Store. Once inside the WSL Ubuntu shell, I updated the distribution: `sudo apt update && sudo apt upgrade`
3. I downloaded and installed the latest version of Miniconda for Linux (64 bit).
4. Following the instructions in our README file
    - I created a new conda environment called `scilk-chem` (`conda create -n scilk-chem python=3.6`),
    - activated it (`source activate scilk-chem`),
    - cloned the `chemdner-pub` branch (`git clone -b chemdner-pub https://github.com/skoblov-lab/SciLK.git`),
    - ran `pip install --no-cache-dir ./SciLK`
5. Additionally, I installed iPython and Jupyter in the same environment to run our demo Jupyter notebooks: `conda install -y ipython jupyter`
6. I downloaded our pretrained models via the Dropbox link in the README file: `wget 
https://www.dropbox.com/s/5z4jqlbjgo15m59/chemdner-collection.tgz?dl=0 -O chemdner-collection.tgz`.
7. I unpacked the archive (`tar -xzf chemdner-collection.tgz`) and moved the unpacked directory into SciLK/notebooks for convenience (`mv chemdner-collection ./SciLK/notebooks`)
8. I downloaded the CHEMDNER testing dataset and saved it as `./Scilk/notebooks/data/testing.abstracts.txt`
9. I changed directory to `./Scilk/notebooks` and fired up a Jupyter server: `jupyter notebook --no-browser`. The server printed out a web-link

<img width="1136" alt="screenshot 2018-11-15 at 14 34 07" src="https://user-images.githubusercontent.com/6906110/48550356-8fa55f00-e8e3-11e8-85cf-515b82c609d9.png">


10. I pasted the web-link into the default browser on Windows (Edge):

<img width="1136" alt="screenshot 2018-11-15 at 14 42 45" src="https://user-images.githubusercontent.com/6906110/48550801-c7f96d00-e8e4-11e8-8ec7-1f1257a2d5aa.png">


11. I opened the `usage-demo.ipynb` notebook, replaced data path in the third cell and executed all cells:

<img width="1680" alt="screenshot 2018-11-15 at 14 39 33" src="https://user-images.githubusercontent.com/6906110/48550655-70f39800-e8e4-11e8-9005-f4de22d0e5c2.png">

**Comment by grayfall** [comment]
@nisch100 We've also updated the `chemdner-pub` branch to account for Windows-specific Python behaviour so that you could install and use SciLK under Windows without WSL. I've successfully tested the same notebook on the same virtual machine in pure Windows. Here are the steps:

1. Download Python 3.7 Miniconda (64bit) for Windows and run the default installer.
2. Open the Anaconda prompt and create a new environment:
```
conda create -n scilk-chem python=3.6
```
3. Activate the environment and install Git:
```
conda activate scilk-chem
conda install git
```
4. Install SciLK branch `chemdner-pub`:
```
pip install --no-cache-dir git+https://github.com/skoblov-lab/SciLK.git@chemdner-pub
```
5. Install Jupyter:
```
conda install ipython jupyter
```
6. `cd` into the notebook directory with downloaded pretrained models and start a Jupyter server
```
jupyter notebook
```
7. Try running the `usage-demo.ipynb`

Let me know, if you need additional assistance.

**Comment by grayfall** [comment]
@nisch100 Was your issue resolved?

**Comment by grayfall** [comment]
@nisch100 I'm closing the issue. Should you face any additional problems with installation on Windows, feel free to reopen the issue.
